version: '3'

services:
  db:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: drone_soccer
      MYSQL_USER: dronesoccer
      MYSQL_PASSWORD: dronepassword
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

  web:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - "9090:80"
    volumes:
      - .:/app/
    links:
      - php
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - app-network

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - .:/app/
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      DB_HOST: db
      DB_NAME: drone_soccer
      DB_USER: dronesoccer
      DB_PASSWORD: Qweszxc!23
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge
