version: '3.8'

services:
  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - "9090:80"
    volumes:
      - ./public:/app/public
    depends_on:
      - php
    networks:
      - app-network

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./public:/app/public
    environment:
      - DB_HOST=db
      - DB_NAME=drone_soccer
      - DB_USER=dronesoccer
      - DB_PASSWORD=password
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: dronesoccer_db
    restart: always
    command: 
      - --authentication-policy=*
      - --host-cache-size=0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=drone_soccer
      - MYSQL_USER=dronesoccer
      - MYSQL_PASSWORD=passowrd
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
